In [1]:
import numpy as np

In [12]:
my_list1 = [1,2,3,4]

In [13]:
my_array1 = np.array(my_list)

In [14]:
my_array1

array([1, 2, 3, 4])

In [15]:
my_list2 = [11,22,33,44]

In [16]:
my_lists = [my_list1, my_list2]

In [17]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [18]:
my_array2 = np.array(my_lists)

In [19]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [20]:
my_array2.shape

(2, 4)

In [21]:
my_array2.dtype

dtype('int32')

In [23]:
np.ones((6,6))

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [24]:
np.empty((2,4))

array([[  2.37663529e-312,   2.35541533e-312,   2.14321575e-312,
          8.48798317e-313],
       [  1.14587773e-312,   1.14587773e-312,   8.70018274e-313,
          0.00000000e+000]])

In [25]:
np.eye((3))

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

単位行列

In [28]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])